name: share data between jobs
on: [push]
jobs:
    job_1:
        runs-on: ubuntu-latest
        steps:
            - shell: bash
              run: |
                expr 3 + 7 > math-homework.txt
            - name: Upload math result for job 1
              uses: actions/upload-artifact@v4
              with:
                  name: homework_pre
                  path: math-homework.txt
    job_2:
        name: Multiply by 9
        needs: job_1
        runs-on: windows-latest
        steps:
            - name: Download math result from job 1
              uses: actions/download-artifact@v4
              with:
                 name: homework_pre
            - shell: bash
              run: |
                value=`cat math-homework.txt`
                expr $value \*9 > math-homework.txt
            - name: Upload math result for job 2
              uses: actions/upload-artifact@v4
              with: 
                   name: homework_final
                   path: math-homework.txt
    job_3:
        name: Display result
        needs: job_2
        runs-on: MacOS-latest
        steps:
            - name: Download math result from job 2
              uses: actions/download-artifact@v4
              with:
                 name: homework_final
            - name: Print the final result
              shell: bash
              run: |
               value=`cat math-homework.txt`
               echo "The final result is $value"
              

